# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=70)),
                ('specialization', multiselectfield.db.fields.MultiSelectField(choices=[('CT', 'Cloud Technology'), ('DS', 'Data Science'), ('IS', 'Information Security'), ('MA', 'Mobile Application')], max_length=11)),
                ('br_abbreviation', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=70)),
                ('course_code', models.CharField(max_length=6)),
                ('credit', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('module_type', models.CharField(choices=[('1', 'C'), ('2', 'CC'), ('3', 'D'), ('4', 'DE'), ('5', 'E'), ('6', 'F'), ('7', 'FE'), ('8', 'G'), ('9', 'GE'), ('10', 'SF')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=70)),
                ('sem_abbreviation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latex.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')])),
                ('sem_abbreviation', models.CharField(max_length=15)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latex.Branch')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latex.Semester'),
        ),
    ]
