# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-13 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization1',
            name='sp2_abbr',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='specialization1',
            name='specialization2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
