# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Hod',
        ),
    ]
