# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('latex', '0002_auto_20180824_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=70)),
                ('semester', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')])),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=70, unique=True)),
                ('sub_code', models.CharField(max_length=6, unique=True)),
                ('module_type', models.CharField(max_length=2, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latex.BranchSem')),
            ],
        ),
    ]
