# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0003_branchsem_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsem',
            name='semester',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')]),
        ),
    ]
