# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0005_auto_20180825_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchsem',
            name='abbrevation',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
