# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-18 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0008_auto_20181018_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(max_length=7),
        ),
    ]
