# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-20 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0015_auto_20181019_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
