# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0035_auto_20181024_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='block',
            field=models.IntegerField(blank=True, help_text='Enter above block value as block id here'),
        ),
    ]
