# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0041_auto_20181028_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionPaper', models.FileField(upload_to='')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latex.Subject')),
            ],
        ),
    ]
