# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0042_questionpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(choices=[(2, '2'), (5, '5'), (10, '10')], null=True),
        ),
    ]
