# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0043_auto_20181029_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.IntegerField(choices=[(30, '30'), (50, '50')], default=30),
            preserve_default=False,
        ),
    ]
