# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0049_auto_20181029_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questioncategory',
            old_name='requried_2mk',
            new_name='required_2mk',
        ),
    ]
