# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0052_remove_questioncategory_marks_in_word'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionCategory',
            new_name='SubjectCategory',
        ),
    ]
