# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0056_auto_20181029_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectcategory',
            options={'verbose_name': 'Subject Category', 'verbose_name_plural': 'Subject Categories'},
        ),
    ]
