# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0059_subject_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='category',
        ),
    ]
