# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-18 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0002_semester_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='sem',
            field=models.IntegerField(default=1),
        ),
    ]
