# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-18 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0006_remove_semester_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='semesters',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='specialization',
        ),
        migrations.RenameField(
            model_name='declaresemester',
            old_name='semesters',
            new_name='semester',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.AddField(
            model_name='specialization',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='latex.DeclareSemester'),
        ),
        migrations.AddField(
            model_name='subject',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='latex.Specialization'),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
