# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-18 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0009_auto_20181018_1525'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set([('specialization', 'subject')]),
        ),
    ]
