# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-18 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0010_auto_20181018_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ManyToManyField(to='latex.Semester'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set([('specialization', 'semester')]),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='specialization',
        ),
    ]
