# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-18 17:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0011_auto_20181018_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='subject',
            name='module_type',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
