# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-21 19:37
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0016_auto_20181020_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '2'), (2, '5'), (3, '10')], max_length=5, null=True),
        ),
    ]
