# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-21 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0017_auto_20181021_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(choices=[(1, '2'), (2, '5'), (3, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='priority',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
    ]
