# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-22 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0021_auto_20181022_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='block',
            field=models.IntegerField(default=32),
            preserve_default=False,
        ),
    ]
