# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0034_auto_20181024_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='block',
            field=models.IntegerField(blank=True, default=33),
            preserve_default=False,
        ),
    ]
