# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0048_auto_20181029_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncategory',
            name='id',
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='total_marks',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
