# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0053_auto_20181029_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latex.SubjectCategory'),
        ),
    ]
