# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0062_auto_20181105_0456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Chapters'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'Semester', 'verbose_name_plural': 'Semesters'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Specialization', 'verbose_name_plural': 'Specializations'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set([]),
        ),
    ]
