# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0064_auto_20181105_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='br_abbr',
            new_name='branch_abbreviation',
        ),
        migrations.RenameField(
            model_name='specialization',
            old_name='specialization1',
            new_name='primary_specialization',
        ),
        migrations.RenameField(
            model_name='specialization',
            old_name='specialization2',
            new_name='secondary_specialization',
        ),
        migrations.RenameField(
            model_name='specialization',
            old_name='abbreviation',
            new_name='specialization_abbreviation',
        ),
    ]
