# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0065_auto_20181108_0542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
    ]
