# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-21 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181019_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subject',
            field=models.ManyToManyField(blank=True, to='latex.Subject'),
        ),
    ]
