# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_loggedinuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedinuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
    ]
