# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20181105_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subjects',
            new_name='subject',
        ),
    ]
