# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20181105_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subject',
            new_name='subjects',
        ),
    ]
