# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-18 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181018_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Head-Of-Department'), (2, 'Faculty')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
