# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-19 13:25
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181018_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subject',
        ),
        migrations.AddField(
            model_name='profile',
            name='subject1',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Subject-1'), ('2', 'Subject-2'), ('3', 'Subject-3'), ('4', 'Subject-4')], max_length=7, null=True),
        ),
    ]
