# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-19 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0014_remove_subject_user'),
        ('accounts', '0004_auto_20181019_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subject1',
        ),
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='latex.Subject'),
        ),
    ]
