# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-19 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0014_remove_subject_user'),
        ('accounts', '0006_auto_20181019_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subject',
        ),
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.ManyToManyField(to='latex.Subject'),
        ),
    ]
