# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('shirt_size', models.CharField(choices=[(b'S', b'Small'), (b'M', b'Medium'), (b'L', b'Large')], max_length=1)),
            ],
        ),
    ]
