# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-18 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=75)),
                ('br_abbr', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DeclareSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semesters', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules', models.CharField(choices=[('1', 'Module 1'), ('2', 'Module 2'), ('3', 'Module 3'), ('4', 'Module 4'), ('5', 'Module 5')], max_length=100)),
                ('question', models.CharField(max_length=300)),
                ('marks', multiselectfield.db.fields.MultiSelectField(choices=[(1, '2'), (2, '5'), (3, '10')], max_length=5)),
                ('priority', multiselectfield.db.fields.MultiSelectField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], max_length=7)),
                ('notes', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latex.Branch')),
                ('semesters', models.ForeignKey(default='Sem-', on_delete=django.db.models.deletion.CASCADE, to='latex.DeclareSemester')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization1', models.CharField(max_length=30)),
                ('specialization2', models.CharField(blank=True, max_length=30)),
                ('abbreviation', models.CharField(max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latex.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=75)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latex.Branch')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latex.Semester')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latex.Subject'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latex.Module'),
        ),
    ]
