# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-31 16:13
from __future__ import unicode_literals

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=75)),
                ('branch_abbreviation', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.IntegerField()),
                ('modules', models.CharField(choices=[('1', 'Module 1'), ('2', 'Module 2'), ('3', 'Module 3'), ('4', 'Module 4'), ('5', 'Module 5')], max_length=100)),
                ('question', ckeditor_uploader.fields.RichTextUploadingField()),
                ('marks', models.IntegerField(choices=[(2, '2'), (5, '5'), (10, '10')], null=True)),
                ('priority', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_specialization', models.CharField(max_length=30)),
                ('secondary_specialization', models.CharField(blank=True, max_length=30)),
                ('specialization_abbreviation', models.CharField(max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latex.Branch')),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=75, unique=True)),
                ('subject_code', models.CharField(blank=True, max_length=6, null=True)),
                ('module_type', models.CharField(blank=True, max_length=2, null=True)),
                ('credits', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('total_marks', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('required_2mk', models.IntegerField(null=True)),
                ('maximum_2mk', models.IntegerField(null=True)),
                ('required_5mk', models.IntegerField(null=True)),
                ('maximum_5mk', models.IntegerField(null=True)),
                ('required_10mk', models.IntegerField(null=True)),
                ('maximum_10mk', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Subject Category',
                'verbose_name_plural': 'Subject Categories',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latex.SubjectCategory'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ManyToManyField(to='latex.Semester'),
        ),
        migrations.AddField(
            model_name='semester',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latex.Specialization'),
        ),
        migrations.AddField(
            model_name='module',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latex.Subject'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latex.Module'),
        ),
    ]
