# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-18 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0003_auto_20181018_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='sem',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
