# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-18 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0004_auto_20181018_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='branch',
        ),
        migrations.AddField(
            model_name='semester',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='latex.Specialization'),
        ),
    ]
