# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-18 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0007_auto_20181018_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='semester',
        ),
        migrations.DeleteModel(
            name='DeclareSemester',
        ),
        migrations.AddField(
            model_name='semester',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latex.Specialization'),
        ),
    ]
