# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-22 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0018_auto_20181021_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='latex.Subject'),
        ),
    ]
