# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-22 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0020_auto_20181022_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
