# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0022_question_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject_id',
        ),
    ]
