# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0023_remove_question_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='block',
            field=models.IntegerField(editable=False),
        ),
    ]
