# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0040_auto_20181027_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(unique=True),
        ),
    ]
