# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0047_auto_20181029_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncategory',
            name='maximum_10mk',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='maximum_2mk',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='maximum_5mk',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='required_10mk',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='required_5mk',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='requried_2mk',
            field=models.IntegerField(null=True),
        ),
    ]
