# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0050_auto_20181029_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='marks_in_word',
            field=models.CharField(default=30, max_length=20),
            preserve_default=False,
        ),
    ]
