# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0054_auto_20181029_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcategory',
            name='total_marks',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
