# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0060_remove_subject_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, to='latex.SubjectCategory'),
            preserve_default=False,
        ),
    ]
