# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0066_auto_20181115_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='subject',
            new_name='module',
        ),
    ]
