# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0068_auto_20181226_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='Subject',
        ),
        migrations.DeleteModel(
            name='QuestionPaper',
        ),
    ]
