# Generated by Django 2.0.7 on 2018-07-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.BigIntegerField()),
                ('profile_pic', models.ImageField(upload_to='')),
                ('employee_id', models.CharField(max_length=8)),
                ('join_date', models.DateField()),
            ],
        ),
    ]
