# Generated by Django 2.0.7 on 2018-08-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
                ('course', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=20)),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
