# Generated by Django 2.1 on 2018-08-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0002_questionblock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionBlock',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
