# Generated by Django 2.1 on 2018-08-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0004_auto_20180810_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='branch',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='question',
            name='chapter',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.CharField(choices=[(0, '2'), (1, '5'), (2, '10')], max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='module',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='question',
            name='priority',
            field=models.CharField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4')], max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='question',
            table='quest',
        ),
    ]
