# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import questionbs.regin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
                ('title', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('answer', models.TextField(max_length=250)),
                ('max_marks', models.FloatField()),
                ('category', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=40)),
                ('course', models.CharField(max_length=35)),
                ('subject', models.CharField(max_length=30)),
                ('module', models.CharField(max_length=30)),
                ('chapter', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=100)),
                ('used_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('contact_number', models.BigIntegerField()),
                ('employee_id', models.CharField(max_length=16)),
                ('date_of_joining', models.DateField()),
                ('gender', models.CharField(max_length=7)),
                ('profile_picture', models.ImageField(upload_to=questionbs.regin.models.get_file_name)),
                ('is_faculty', models.BooleanField(default=True)),
                ('is_hod', models.BooleanField(default=False)),
                ('departmenet', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regin.UserProfile'),
        ),
    ]
